// @ts-check
/** @type {import('@stryker-mutator/api/core').PartialStrykerOptions} */
const config = {
  cleanTempDir: "always",
  incremental: true,
  incrementalFile: "tests/stryker/incremental/incremental.json",
  checkers: ["typescript"],
  tsconfigFile: "tsconfig.json",
  testRunner: "vitest",
  ignoreStatic: true,
  plugins: [
    "@stryker-mutator/vitest-runner",
    "@stryker-mutator/typescript-checker",
  ],
  ignorePatterns: [
    ".github/",
    ".husky/",
    ".run/",
    ".idea/",
    "dist/",
    "config/commitlint",
    "config/cucumber",
    "config/eslint",
    "config/lint-staged",
    "config/stryker",
    "tests/stryker",
    "tests/unit/coverage",
    "scripts/",
    "server/",
    ".editorconfig",
    ".npmrc",
    ".nvmrc",
    "release.config.mjs",
    ".DS_Store",
    ".validate-branch-namerc.json",
    "CHANGELOG.md",
    "LICENSE",
    "pnpm-lock.yaml",
    "sonar-project.properties",
    "README.md",
    "eslint.config.ts",
  ],
  vitest: { configFile: "config/vitest/vitest.global-unit-tests-config.ts" },
  reporters: ["clear-text", "progress", "html", "json"],
  htmlReporter: { fileName: "tests/stryker/coverage/index.html" },
  jsonReporter: { fileName: "tests/stryker/coverage/mutation.json" },
  thresholds: {
    high: 100,
    low: 100,
    break: 100,
  },
  dryRunTimeoutMinutes: 10,
  disableTypeChecks: true,
  packageManager: "pnpm",
};

export default config;